package com.example.trashcompass

import android.content.Context
import org.json.JSONObject
import java.util.Locale

/**
 * One thing a person can ask the compass to find.
 *
 * [target] is what the rest of the app searches for: either the name of a
 * [TagRepository] catalog entry or a tag filter such as
 * "amenity=fast_food&cuisine=pizza". [label] is the plain-language name and
 * [hint] a short second line for the result list.
 */
data class Feature(val label: String, val target: String, val hint: String)

/** "waste_basket" -> "Waste Basket" */
fun prettyTagName(raw: String): String =
    raw.replace('_', ' ').split(' ').filter { it.isNotEmpty() }.joinToString(" ") { word ->
        word.replaceFirstChar {
            if (it.isLowerCase()) it.titlecase(Locale.getDefault()) else it.toString()
        }
    }

/**
 * Offline, plain-language index of OpenStreetMap feature types.
 *
 * It combines the app's own curated catalog with the preset list of the iD
 * editor (assets/osm_presets.tsv, generated by tools/build_presets.py from
 * openstreetmap/id-tagging-schema, ISC licence). The presets are what OSM
 * mappers themselves pick from, and each one carries the everyday names and
 * search words people actually use -- "bin", "garbage", "litter" and
 * "rubbish" all lead to the trash can -- so nobody has to know OSM notation.
 * Anything rarer than that is covered online by [TaginfoClient].
 */
object FeatureIndex {

    private class Entry(
        val feature: Feature,
        val curated: Boolean,
        val pairs: List<Pair<String, String>> // tag filter of a preset; empty for catalog entries
    ) {
        val name = feature.label.lowercase(Locale.ROOT)
        val nameWords = words(name)
        var altPhrases: List<String> = emptyList()
        var altWords: Set<String> = emptySet()

        fun setAlts(alts: List<String>) {
            altPhrases = alts.map { it.lowercase(Locale.ROOT) }
            altWords = altPhrases.flatMap { words(it) }.toSet()
        }
    }

    @Volatile private var entries: List<Entry> = emptyList()
    @Volatile private var presetsByTag: Map<String, List<Entry>> = emptyMap()

    private fun words(text: String): List<String> =
        text.split(Regex("[^\\p{L}\\p{N}]+")).filter { it.isNotEmpty() }

    /** Reads the bundled preset list. Safe to call more than once; call off the main thread. */
    @Synchronized
    fun load(context: Context) {
        if (entries.isNotEmpty()) return
        val list = ArrayList<Entry>()
        val catalogByName = HashMap<String, Entry>()
        for ((category, items) in TagRepository.categories) {
            for (name in items.keys) {
                val e = Entry(Feature(name, name, category), curated = true, pairs = emptyList())
                list.add(e)
                catalogByName[e.name] = e
            }
        }

        val byTag = HashMap<String, MutableList<Entry>>()
        try {
            context.assets.open("osm_presets.tsv").bufferedReader().useLines { lines ->
                for (line in lines) {
                    val cols = line.split('\t')
                    if (cols.size < 3) continue
                    val alts = cols[1].split('|').filter { it.isNotEmpty() }
                    val pairs = cols[2].split('&').mapNotNull {
                        val k = it.substringBefore('=', "")
                        if (k.isEmpty()) null else k to it.substringAfter('=')
                    }
                    if (pairs.isEmpty()) continue
                    val hint = alts.take(4).joinToString(", ")
                    val e = Entry(Feature(cols[0], cols[2], hint), curated = false, pairs = pairs)
                    e.setAlts(alts)
                    for ((k, v) in pairs) byTag.getOrPut("$k=$v") { ArrayList() }.add(e)

                    // The curated entry of the same name wins in search (its query is
                    // usually broader), but inherits the preset's everyday words.
                    val curated = catalogByName[e.name]
                    if (curated != null) {
                        curated.setAlts(curated.altPhrases + alts)
                    } else {
                        list.add(e)
                    }
                }
            }
        } catch (e: Exception) {
            // Asset missing or unreadable: the curated catalog alone still works.
        }
        presetsByTag = byTag
        entries = list
    }

    /**
     * Best matches for plain words, best first. Every word typed must match the
     * start of a word in the feature's name or in its other names and search
     * words, so "water drink" finds "Drinking Water" and "garbage" finds
     * "Trash Can".
     */
    fun search(query: String, limit: Int = 40): List<Feature> {
        val q = query.trim().lowercase(Locale.ROOT)
        val qWords = words(q)
        if (qWords.isEmpty()) return emptyList()

        val scored = ArrayList<Pair<Int, Entry>>()
        for (e in entries) {
            val score = score(e, q, qWords) ?: continue
            scored.add(score to e)
        }
        scored.sortWith(
            compareBy<Pair<Int, Entry>> { it.first }
                .thenBy { if (it.second.curated) 0 else 1 }
                .thenBy { it.second.name.length }
        )

        val seenLabels = HashSet<String>()
        val out = ArrayList<Feature>()
        for ((_, e) in scored) {
            if (!seenLabels.add(e.name + "|" + e.feature.hint)) continue
            out.add(e.feature)
            if (out.size >= limit) break
        }
        return out
    }

    /** Lower is better; null means no match. */
    private fun score(e: Entry, q: String, qWords: List<String>): Int? {
        if (e.name == q) return 0
        if (e.name.startsWith(q)) return 10
        if (qWords.all { matchesAny(it, e.nameWords) }) return 20
        if (e.altPhrases.any { it == q }) return 30
        var inAltsOnly = 0
        for (w in qWords) {
            if (matchesAny(w, e.nameWords)) continue
            if (matchesAny(w, e.altWords)) inAltsOnly++ else return null
        }
        return 40 + inAltsOnly
    }

    /** Prefix match, forgiving simple plurals ("benches", "toilets"). */
    private fun matchesAny(word: String, candidates: Collection<String>): Boolean {
        if (candidates.any { it.startsWith(word) }) return true
        if (word.length > 3 && word.endsWith("es") && candidates.any { it.startsWith(word.dropLast(2)) }) return true
        if (word.length > 3 && word.endsWith("s") && candidates.any { it.startsWith(word.dropLast(1)) }) return true
        return false
    }

    /**
     * The most specific preset describing an OSM element with these [tags], or
     * null if only a catch-all preset (such as "any shop") or nothing matches.
     */
    fun describe(tags: JSONObject): Feature? {
        var best: Entry? = null
        var bestScore = 0
        val keys = tags.keys()
        while (keys.hasNext()) {
            val k = keys.next()
            val v = tags.optString(k)
            for (lookup in arrayOf("$k=$v", "$k=*")) {
                val candidates = presetsByTag[lookup] ?: continue
                for (e in candidates) {
                    var score = 0
                    for ((pk, pv) in e.pairs) {
                        if (!tags.has(pk)) { score = -1; break }
                        if (pv == "*") score += 1
                        else if (tags.optString(pk) == pv) score += 10
                        else { score = -1; break }
                    }
                    if (score > bestScore) { bestScore = score; best = e }
                }
            }
        }
        return if (bestScore >= 10) best?.feature else null
    }
}
