package com.example.trashcompass

/**
 * The catalog of searchable OSM features.
 *
 * QUERY SYNTAX for the values:
 *  - "key=value"                       exact tag match
 *  - "key~regex"                       regex tag match
 *  - clauses joined by " OR "          each clause searched separately
 *  - filters inside a clause joined by "&"  (all must match), e.g.
 *    "amenity=recycling&recycling_type=centre"
 *
 * Everything here is queried as nwr (node + way + relation), so areas
 * and multipolygons are found too.
 *
 * Tag names follow the OpenStreetMap wiki "Map Features" page and the
 * individual key pages. Coverage on the ground still depends on what
 * mappers in your area have actually tagged.
 *
 * [categories] drives the "Browse All" picker UI; [mapping] is the
 * flattened lookup used by search and the Overpass query builder.
 */
object TagRepository {

    val categories: Map<String, Map<String, String>> = linkedMapOf(

        "Waste & Recycling" to linkedMapOf(
            "Trash Can" to "amenity=waste_basket OR amenity=waste_disposal OR bin=yes OR rubbish=yes",
            "Trash Bin" to "amenity=waste_basket OR amenity=waste_disposal OR bin=yes OR rubbish=yes",
            "Waste Disposal (Dumpster)" to "amenity=waste_disposal",
            "Dog Waste Bin" to "amenity=waste_basket&waste=dog_excrement OR vending=excrement_bags",
            "Dog Poop Bags" to "vending=excrement_bags",
            "Recycling (Any)" to "amenity=recycling",
            "Recycling Bin" to "amenity=recycling",
            "Recycling Container" to "amenity=recycling&recycling_type=container",
            "Recycling Centre" to "amenity=recycling&recycling_type=centre",
            "Glass Recycling" to "recycling:glass=yes OR recycling:glass_bottles=yes",
            "Glass Bottle Recycling" to "recycling:glass_bottles=yes",
            "Paper Recycling" to "recycling:paper=yes",
            "Cardboard Recycling" to "recycling:cardboard=yes",
            "Clothes Recycling" to "recycling:clothes=yes",
            "Shoes Recycling" to "recycling:shoes=yes",
            "Metal Recycling" to "recycling:cans=yes OR recycling:scrap_metal=yes",
            "Scrap Metal Recycling" to "recycling:scrap_metal=yes",
            "Plastic Recycling" to "recycling:plastic=yes OR recycling:plastic_bottles=yes",
            "Plastic Bottle Recycling" to "recycling:plastic_bottles=yes",
            "Battery Recycling" to "recycling:batteries=yes",
            "Green Waste Recycling" to "recycling:green_waste=yes",
            "Sanitary Dump Station" to "amenity=sanitary_dump_station",
            "Waste Transfer Station" to "amenity=waste_transfer_station",
            "Landfill" to "landuse=landfill",
            "Wastewater Plant" to "man_made=wastewater_plant"
        ),

        "Everyday Essentials" to linkedMapOf(
            "Public Toilet" to "amenity=toilets OR toilets~yes|designated|public",
            "Toilets" to "amenity=toilets",
            "Water Fountain" to "amenity=drinking_water",
            "Drinking Water" to "amenity=drinking_water",
            "Defibrillator (AED)" to "emergency=defibrillator",
            "Bench" to "amenity=bench",
            "ATM" to "amenity=atm",
            "Post Box" to "amenity=post_box",
            "Shelter" to "amenity=shelter",
            "Telephone" to "amenity=telephone",
            "Clock" to "amenity=clock",
            "Device Charging Station" to "amenity=device_charging_station",
            "Smoking Area" to "amenity=smoking_area",
            "Picnic Table" to "leisure=picnic_table"
        ),

        "Food & Drink" to linkedMapOf(
            "Bar" to "amenity=bar",
            "BBQ / Grill" to "amenity=bbq",
            "Biergarten" to "amenity=biergarten",
            "Cafe" to "amenity=cafe",
            "Canteen" to "amenity=canteen",
            "Fast Food" to "amenity=fast_food",
            "Food Court" to "amenity=food_court",
            "Food Sharing" to "amenity=food_sharing",
            "Ice Cream" to "amenity=ice_cream",
            "Pub" to "amenity=pub",
            "Restaurant" to "amenity=restaurant",
            "Water Point" to "amenity=water_point"
        ),

        "Education" to linkedMapOf(
            "College" to "amenity=college",
            "Driving School" to "amenity=driving_school",
            "Kindergarten" to "amenity=kindergarten",
            "Language School" to "amenity=language_school",
            "Library" to "amenity=library",
            "Music School" to "amenity=music_school",
            "Prep School" to "amenity=prep_school",
            "Research Institute" to "amenity=research_institute",
            "School" to "amenity=school",
            "Toy Library" to "amenity=toy_library",
            "Training Centre" to "amenity=training",
            "University" to "amenity=university"
        ),

        "Transport: Road & Cycle" to linkedMapOf(
            "Bicycle Parking" to "amenity=bicycle_parking",
            "Bicycle Rental" to "amenity=bicycle_rental",
            "Bicycle Repair Station" to "amenity=bicycle_repair_station",
            "Bicycle Wash" to "amenity=bicycle_wash",
            "Compressed Air (Tyre Pump)" to "amenity=compressed_air",
            "Bus Station" to "amenity=bus_station",
            "Car Rental" to "amenity=car_rental",
            "Car Sharing" to "amenity=car_sharing",
            "Car Wash" to "amenity=car_wash",
            "EV Charging Station" to "amenity=charging_station",
            "Fuel Station" to "amenity=fuel",
            "Grit Bin" to "amenity=grit_bin",
            "Motorcycle Parking" to "amenity=motorcycle_parking",
            "Parking" to "amenity=parking",
            "Parking Entrance" to "amenity=parking_entrance",
            "Parking Space" to "amenity=parking_space",
            "Taxi Stand" to "amenity=taxi",
            "Ticket Validator" to "amenity=ticket_validator",
            "Vehicle Inspection" to "amenity=vehicle_inspection",
            "Weighbridge" to "amenity=weighbridge"
        ),

        "Transport: Public Transit & Rail" to linkedMapOf(
            "Bus Stop" to "highway=bus_stop",
            "Public Transport Platform" to "public_transport=platform",
            "Public Transport Station" to "public_transport=station",
            "Public Transport Stop" to "public_transport=stop_position",
            "Train Station" to "railway=station",
            "Railway Halt" to "railway=halt",
            "Railway Platform" to "railway=platform",
            "Subway Entrance" to "railway=subway_entrance",
            "Subway Station" to "station=subway",
            "Light Rail Station" to "station=light_rail",
            "Monorail Station" to "station=monorail",
            "Tram Stop" to "railway=tram_stop",
            "Level Crossing" to "railway=level_crossing",
            "Railway Buffer Stop" to "railway=buffer_stop",
            "Railway Signal" to "railway=signal",
            "Railway Switch" to "railway=switch",
            "Railway Turntable" to "railway=turntable"
        ),

        "Transport: Air" to linkedMapOf(
            "Airport" to "aeroway=aerodrome",
            "Airport Terminal" to "aeroway=terminal",
            "Airport Gate" to "aeroway=gate",
            "Helipad" to "aeroway=helipad",
            "Hangar" to "aeroway=hangar",
            "Runway" to "aeroway=runway",
            "Taxiway" to "aeroway=taxiway",
            "Windsock" to "aeroway=windsock"
        ),

        "Transport: Water" to linkedMapOf(
            "Boat Rental" to "amenity=boat_rental",
            "Boat Sharing" to "amenity=boat_sharing",
            "Boatyard" to "waterway=boatyard",
            "Dam" to "waterway=dam",
            "Dock" to "waterway=dock",
            "Ferry Terminal" to "amenity=ferry_terminal",
            "Lock Gate" to "waterway=lock_gate",
            "Marina" to "leisure=marina",
            "Pier" to "man_made=pier",
            "Slipway" to "leisure=slipway",
            "Weir" to "waterway=weir",
            "Lighthouse" to "man_made=lighthouse",
            "Beacon" to "man_made=beacon"
        ),

        "Financial" to linkedMapOf(
            "Bank" to "amenity=bank",
            "Bureau de Change" to "amenity=bureau_de_change",
            "Mobile Money Agent" to "amenity=mobile_money_agent",
            "Money Transfer" to "amenity=money_transfer",
            "Payment Terminal" to "amenity=payment_terminal"
        ),

        "Healthcare" to linkedMapOf(
            "Baby Hatch" to "amenity=baby_hatch",
            "Blood Donation" to "amenity=blood_donation OR healthcare=blood_donation",
            "Clinic" to "amenity=clinic OR healthcare=clinic",
            "Dentist" to "amenity=dentist OR healthcare=dentist",
            "Doctor" to "amenity=doctors OR healthcare=doctor",
            "Hospital" to "amenity=hospital OR healthcare=hospital",
            "Hospice" to "healthcare=hospice",
            "Nursing Home" to "amenity=nursing_home",
            "Pharmacy" to "amenity=pharmacy OR healthcare=pharmacy",
            "Physiotherapist" to "healthcare=physiotherapist",
            "Psychotherapist" to "healthcare=psychotherapist",
            "Optometrist" to "healthcare=optometrist",
            "Audiologist" to "healthcare=audiologist",
            "Podiatrist" to "healthcare=podiatrist",
            "Midwife" to "healthcare=midwife",
            "Speech Therapist" to "healthcare=speech_therapist",
            "Occupational Therapist" to "healthcare=occupational_therapist",
            "Dialysis" to "healthcare=dialysis",
            "Medical Laboratory" to "healthcare=laboratory",
            "Rehabilitation" to "healthcare=rehabilitation",
            "Vaccination Centre" to "healthcare=vaccination_centre",
            "Alternative Medicine" to "healthcare=alternative",
            "Social Facility" to "amenity=social_facility",
            "Veterinary" to "amenity=veterinary"
        ),

        "Entertainment, Arts & Culture" to linkedMapOf(
            "Arts Centre" to "amenity=arts_centre",
            "Brothel" to "amenity=brothel",
            "Casino" to "amenity=casino",
            "Cinema" to "amenity=cinema",
            "Community Centre" to "amenity=community_centre",
            "Conference Centre" to "amenity=conference_centre",
            "Events Venue" to "amenity=events_venue",
            "Exhibition Centre" to "amenity=exhibition_centre",
            "Fountain" to "amenity=fountain",
            "Gambling" to "amenity=gambling",
            "Hookah Lounge" to "amenity=hookah_lounge",
            "Karaoke Box" to "amenity=karaoke_box",
            "Love Hotel" to "amenity=love_hotel",
            "Music Venue" to "amenity=music_venue",
            "Nightclub" to "amenity=nightclub",
            "Planetarium" to "amenity=planetarium",
            "Public Bookcase" to "amenity=public_bookcase",
            "Social Centre" to "amenity=social_centre",
            "Stage" to "amenity=stage",
            "Stripclub" to "amenity=stripclub",
            "Studio" to "amenity=studio",
            "Swingerclub" to "amenity=swingerclub",
            "Theatre" to "amenity=theatre"
        ),

        "Public Services" to linkedMapOf(
            "Courthouse" to "amenity=courthouse",
            "Embassy" to "amenity=embassy OR office=diplomatic",
            "Fire Station" to "amenity=fire_station",
            "Police" to "amenity=police",
            "Post Depot" to "amenity=post_depot",
            "Post Office" to "amenity=post_office",
            "Prison" to "amenity=prison",
            "Ranger Station" to "amenity=ranger_station",
            "Register Office" to "office=register",
            "Town Hall" to "amenity=townhall"
        ),

        "Facilities & Street Furniture" to linkedMapOf(
            "Binoculars (Public)" to "amenity=binoculars",
            "Check-in" to "amenity=check_in",
            "Dog Toilet" to "amenity=dog_toilet",
            "Dressing Room" to "amenity=dressing_room",
            "Give Box" to "amenity=give_box",
            "Internet Cafe" to "amenity=internet_cafe",
            "Kitchen (Public)" to "amenity=kitchen",
            "Kneipp Water Cure" to "amenity=kneipp_water_cure",
            "Lounger" to "amenity=lounger",
            "Luggage Locker" to "amenity=locker",
            "Marketplace" to "amenity=marketplace",
            "Monastery" to "amenity=monastery",
            "Parcel Locker" to "amenity=parcel_locker",
            "Photo Booth" to "amenity=photo_booth",
            "Place of Mourning" to "amenity=place_of_mourning",
            "Place of Worship" to "amenity=place_of_worship",
            "Public Bath" to "amenity=public_bath",
            "Reception Desk" to "amenity=reception_desk",
            "Refugee Site" to "amenity=refugee_site",
            "Shopping Trolley Bay" to "amenity=trolley_bay",
            "Shower" to "amenity=shower",
            "Vending Machine (Any)" to "amenity=vending_machine",
            "Watering Place" to "amenity=watering_place"
        ),

        "Other Amenities" to linkedMapOf(
            "Animal Boarding" to "amenity=animal_boarding",
            "Animal Breeding" to "amenity=animal_breeding",
            "Animal Shelter" to "amenity=animal_shelter",
            "Animal Training" to "amenity=animal_training",
            "Baking Oven" to "amenity=baking_oven",
            "Childcare" to "amenity=childcare",
            "Crematorium" to "amenity=crematorium",
            "Dive Centre" to "amenity=dive_centre",
            "Feeding Place (Animals)" to "amenity=feeding_place",
            "Funeral Hall" to "amenity=funeral_hall",
            "Graveyard" to "amenity=graveyard",
            "Hunting Stand" to "amenity=hunting_stand",
            "Letter Box" to "amenity=letter_box",
            "Loading Dock" to "amenity=loading_dock",
            "Mortuary" to "amenity=mortuary",
            "Public Building" to "amenity=public_building"
        ),

        "Shops: Food & Drink" to linkedMapOf(
            "Alcohol Shop" to "shop=alcohol",
            "Bakery" to "shop=bakery",
            "Beverage Shop" to "shop=beverages",
            "Brewing Supplies" to "shop=brewing_supplies",
            "Butcher" to "shop=butcher",
            "Cheese Shop" to "shop=cheese",
            "Chocolate Shop" to "shop=chocolate",
            "Coffee Shop" to "shop=coffee",
            "Confectionery" to "shop=confectionery",
            "Convenience Store" to "shop=convenience",
            "Dairy" to "shop=dairy",
            "Deli" to "shop=deli",
            "Farm Shop" to "shop=farm",
            "Food Shop" to "shop=food",
            "Frozen Food" to "shop=frozen_food",
            "Greengrocer" to "shop=greengrocer",
            "Health Food" to "shop=health_food",
            "Ice Cream Shop" to "shop=ice_cream",
            "Nut Shop" to "shop=nuts",
            "Pasta Shop" to "shop=pasta",
            "Pastry Shop" to "shop=pastry",
            "Seafood Shop" to "shop=seafood",
            "Spices Shop" to "shop=spices",
            "Supermarket" to "shop=supermarket",
            "Tea Shop" to "shop=tea",
            "Water Shop" to "shop=water",
            "Wine Shop" to "shop=wine"
        ),

        "Shops: General" to linkedMapOf(
            "Charity Shop" to "shop=charity",
            "Department Store" to "shop=department_store",
            "General Store" to "shop=general",
            "Kiosk" to "shop=kiosk",
            "Mall" to "shop=mall",
            "Pawnbroker" to "shop=pawnbroker",
            "Second Hand" to "shop=second_hand",
            "Variety Store" to "shop=variety_store",
            "Wholesale" to "shop=wholesale"
        ),

        "Shops: Clothing & Accessories" to linkedMapOf(
            "Baby Goods" to "shop=baby_goods",
            "Bag Shop" to "shop=bag",
            "Boutique" to "shop=boutique",
            "Clothes Shop" to "shop=clothes",
            "Fabric Shop" to "shop=fabric",
            "Fashion Accessories" to "shop=fashion_accessories",
            "Jewelry" to "shop=jewelry",
            "Leather Shop" to "shop=leather",
            "Sewing Shop" to "shop=sewing",
            "Shoe Repair" to "shop=shoe_repair",
            "Shoe Shop" to "shop=shoes",
            "Tailor" to "shop=tailor",
            "Watches" to "shop=watches",
            "Wool" to "shop=wool"
        ),

        "Shops: Health & Beauty" to linkedMapOf(
            "Beauty Shop" to "shop=beauty",
            "Chemist" to "shop=chemist",
            "Cosmetics" to "shop=cosmetics",
            "Drugstore" to "shop=drugstore",
            "Erotic Shop" to "shop=erotic",
            "Hairdresser" to "shop=hairdresser",
            "Hairdresser Supply" to "shop=hairdresser_supply",
            "Hearing Aids" to "shop=hearing_aids",
            "Herbalist" to "shop=herbalist",
            "Massage Shop" to "shop=massage",
            "Medical Supply" to "shop=medical_supply",
            "Nutrition Supplements" to "shop=nutrition_supplements",
            "Optician" to "shop=optician",
            "Perfumery" to "shop=perfumery",
            "Piercing" to "shop=piercing",
            "Tattoo" to "shop=tattoo"
        ),

        "Shops: DIY, Garden & Household" to linkedMapOf(
            "Agrarian" to "shop=agrarian",
            "Appliance" to "shop=appliance",
            "Bathroom Furnishing" to "shop=bathroom_furnishing",
            "Country Store" to "shop=country_store",
            "Do It Yourself (DIY)" to "shop=doityourself",
            "Electrical" to "shop=electrical",
            "Energy" to "shop=energy",
            "Fireplace" to "shop=fireplace",
            "Florist" to "shop=florist",
            "Garden Centre" to "shop=garden_centre",
            "Garden Furniture" to "shop=garden_furniture",
            "Gas" to "shop=gas",
            "Glaziery" to "shop=glaziery",
            "Hardware" to "shop=hardware",
            "Houseware" to "shop=houseware",
            "Locksmith" to "shop=locksmith",
            "Paint" to "shop=paint",
            "Pottery Shop" to "shop=pottery",
            "Security" to "shop=security",
            "Tool Hire" to "shop=tool_hire",
            "Trade" to "shop=trade"
        ),

        "Shops: Furniture & Interior" to linkedMapOf(
            "Antiques" to "shop=antiques",
            "Bed Shop" to "shop=bed",
            "Candles" to "shop=candles",
            "Carpet" to "shop=carpet",
            "Curtain" to "shop=curtain",
            "Doors" to "shop=doors",
            "Flooring" to "shop=flooring",
            "Furniture" to "shop=furniture",
            "Household Linen" to "shop=household_linen",
            "Interior Decoration" to "shop=interior_decoration",
            "Kitchen" to "shop=kitchen",
            "Lighting" to "shop=lighting",
            "Tiles" to "shop=tiles",
            "Window Blind" to "shop=window_blind"
        ),

        "Shops: Electronics" to linkedMapOf(
            "Computer" to "shop=computer",
            "Electronics" to "shop=electronics",
            "Hifi" to "shop=hifi",
            "Mobile Phone" to "shop=mobile_phone",
            "Printer Ink" to "shop=printer_ink",
            "Radiotechnics" to "shop=radiotechnics",
            "Telecommunication" to "shop=telecommunication",
            "Vacuum Cleaner" to "shop=vacuum_cleaner",
            "Video Games" to "shop=video_games"
        ),

        "Shops: Outdoors & Vehicles" to linkedMapOf(
            "ATV" to "shop=atv",
            "Bicycle Shop" to "shop=bicycle",
            "Boat Shop" to "shop=boat",
            "Car Parts" to "shop=car_parts",
            "Car Repair" to "shop=car_repair",
            "Car Shop" to "shop=car",
            "Caravan" to "shop=caravan",
            "Fishing Shop" to "shop=fishing",
            "Fuel Shop" to "shop=fuel",
            "Golf Shop" to "shop=golf",
            "Hunting Shop" to "shop=hunting",
            "Military Surplus" to "shop=military_surplus",
            "Motorcycle Repair" to "shop=motorcycle_repair",
            "Motorcycle Shop" to "shop=motorcycle",
            "Outdoor" to "shop=outdoor",
            "Scuba Diving Shop" to "shop=scuba_diving",
            "Ski Rental" to "shop=ski",
            "Sled Rental" to "shop=sled",
            "Snowmobile" to "shop=snowmobile",
            "Sports Shop" to "shop=sports",
            "Surf" to "shop=surf",
            "Swimming Pool Shop" to "shop=swimming_pool",
            "Trailer" to "shop=trailer",
            "Truck" to "shop=truck",
            "Tyres" to "shop=tyres"
        ),

        "Shops: Hobbies, Arts & Books" to linkedMapOf(
            "Anime" to "shop=anime",
            "Art" to "shop=art",
            "Bookmaker" to "shop=bookmaker",
            "Books" to "shop=books",
            "Camera" to "shop=camera",
            "Collector" to "shop=collector",
            "Copy Shop" to "shop=copyshop",
            "Craft Shop" to "shop=craft",
            "Frame" to "shop=frame",
            "Games" to "shop=games",
            "Gift" to "shop=gift",
            "Hobby Shop" to "shop=hobby",
            "Lottery" to "shop=lottery",
            "Model" to "shop=model",
            "Music" to "shop=music",
            "Musical Instrument Shop" to "shop=musical_instrument",
            "Newsagent" to "shop=newsagent",
            "Photo" to "shop=photo",
            "Pyrotechnics" to "shop=pyrotechnics",
            "Stationery" to "shop=stationery",
            "Ticket" to "shop=ticket",
            "Tobacco" to "shop=tobacco",
            "Toys" to "shop=toys",
            "Trophy" to "shop=trophy",
            "Video" to "shop=video"
        ),

        "Shops: Other" to linkedMapOf(
            "Cannabis" to "shop=cannabis",
            "Dry Cleaning" to "shop=dry_cleaning",
            "E-Cigarette" to "shop=e-cigarette",
            "Funeral Directors" to "shop=funeral_directors",
            "Laundry" to "shop=laundry",
            "Money Lender" to "shop=money_lender",
            "Outpost" to "shop=outpost",
            "Party" to "shop=party",
            "Pest Control" to "shop=pest_control",
            "Pet" to "shop=pet",
            "Pet Grooming" to "shop=pet_grooming",
            "Religion" to "shop=religion",
            "Rental" to "shop=rental",
            "Storage Rental" to "shop=storage_rental",
            "Travel Agency" to "shop=travel_agency",
            "Vacant Shop" to "shop=vacant",
            "Weapons" to "shop=weapons"
        ),

        "Offices" to linkedMapOf(
            "Office (General)" to "office=yes",
            "Accountant" to "office=accountant",
            "Adoption Agency" to "office=adoption_agency",
            "Advertising Agency" to "office=advertising_agency",
            "Architect" to "office=architect",
            "Association" to "office=association",
            "Charity Office" to "office=charity",
            "Company" to "office=company",
            "Consulting" to "office=consulting",
            "Courier" to "office=courier",
            "Coworking" to "office=coworking",
            "Diplomatic" to "office=diplomatic",
            "Educational" to "office=educational",
            "Employment Agency" to "office=employment_agency",
            "Energy Supplier" to "office=energy_supplier",
            "Engineer" to "office=engineer",
            "Estate Agent" to "office=estate_agent",
            "Financial" to "office=financial",
            "Forestry" to "office=forestry",
            "Foundation" to "office=foundation",
            "Government" to "office=government",
            "Graphic Design" to "office=graphic_design",
            "Guide" to "office=guide",
            "Harbour Master" to "office=harbour_master",
            "Insurance" to "office=insurance",
            "IT" to "office=it",
            "Lawyer" to "office=lawyer",
            "Logistics" to "office=logistics",
            "Moving Company" to "office=moving_company",
            "Newspaper" to "office=newspaper",
            "NGO" to "office=ngo",
            "Notary" to "office=notary",
            "Political Party" to "office=political_party",
            "Private Investigator" to "office=private_investigator",
            "Property Management" to "office=property_management",
            "Quango" to "office=quango",
            "Religion Office" to "office=religion",
            "Research Office" to "office=research",
            "Security Office" to "office=security",
            "Surveyor" to "office=surveyor",
            "Tax Advisor" to "office=tax_advisor",
            "Telecommunication Office" to "office=telecommunication",
            "Travel Agent" to "office=travel_agent",
            "Union" to "office=union",
            "Water Utility" to "office=water_utility"
        ),

        "Crafts & Trades" to linkedMapOf(
            "Craft (General)" to "craft=yes",
            "Agricultural Engines" to "craft=agricultural_engines",
            "Basket Maker" to "craft=basket_maker",
            "Beekeeper" to "craft=beekeeper",
            "Blacksmith" to "craft=blacksmith",
            "Boatbuilder" to "craft=boatbuilder",
            "Bookbinder" to "craft=bookbinder",
            "Brewery" to "craft=brewery",
            "Builder" to "craft=builder",
            "Cabinet Maker" to "craft=cabinet_maker",
            "Carpenter" to "craft=carpenter",
            "Carpet Layer" to "craft=carpet_layer",
            "Caterer" to "craft=caterer",
            "Chimney Sweeper" to "craft=chimney_sweeper",
            "Clockmaker" to "craft=clockmaker",
            "Confectionery (Craft)" to "craft=confectionery",
            "Dental Technician" to "craft=dental_technician",
            "Distillery" to "craft=distillery",
            "Door Construction" to "craft=door_construction",
            "Dressmaker" to "craft=dressmaker",
            "Electrician" to "craft=electrician",
            "Embroiderer" to "craft=embroiderer",
            "Engraver" to "craft=engraver",
            "Floorer" to "craft=floorer",
            "Gardener" to "craft=gardener",
            "Glazier" to "craft=glazier",
            "Goldsmith" to "craft=goldsmith",
            "Grinding Mill" to "craft=grinding_mill",
            "Handicraft" to "craft=handicraft",
            "Hvac" to "craft=hvac",
            "Insulation" to "craft=insulation",
            "Jeweller" to "craft=jeweller",
            "Joiner" to "craft=joiner",
            "Key Cutter" to "craft=key_cutter",
            "Locksmith (Craft)" to "craft=locksmith",
            "Metal Construction" to "craft=metal_construction",
            "Mint" to "craft=mint",
            "Musical Instrument Maker" to "craft=musical_instrument",
            "Oil Mill" to "craft=oil_mill",
            "Optician (Craft)" to "craft=optician",
            "Organ Builder" to "craft=organ_builder",
            "Painter" to "craft=painter",
            "Parquet Layer" to "craft=parquet_layer",
            "Photographer" to "craft=photographer",
            "Photographic Laboratory" to "craft=photographic_laboratory",
            "Piano Tuner" to "craft=piano_tuner",
            "Plasterer" to "craft=plasterer",
            "Plumber" to "craft=plumber",
            "Pottery (Craft)" to "craft=pottery",
            "Printer" to "craft=printer",
            "Print Shop" to "craft=print_shop",
            "Rigger" to "craft=rigger",
            "Roofer" to "craft=roofer",
            "Saddler" to "craft=saddler",
            "Sailmaker" to "craft=sailmaker",
            "Sawmill" to "craft=sawmill",
            "Scaffolder" to "craft=scaffolder",
            "Sculptor" to "craft=sculptor",
            "Shoemaker" to "craft=shoemaker",
            "Sign Maker" to "craft=sign_maker",
            "Stand Builder" to "craft=stand_builder",
            "Stonemason" to "craft=stonemason",
            "Stove Fitter" to "craft=stove_fitter",
            "Tailor (Craft)" to "craft=tailor",
            "Tiler" to "craft=tiler",
            "Tinsmith" to "craft=tinsmith",
            "Toolmaker" to "craft=toolmaker",
            "Turner" to "craft=turner",
            "Upholsterer" to "craft=upholsterer",
            "Watchmaker" to "craft=watchmaker",
            "Water Well Drilling" to "craft=water_well_drilling",
            "Window Construction" to "craft=window_construction",
            "Winery" to "craft=winery"
        ),

        "Emergency" to linkedMapOf(
            "Ambulance Station" to "emergency=ambulance_station",
            "Assembly Point" to "emergency=assembly_point",
            "Defibrillator" to "emergency=defibrillator",
            "Emergency Access Point" to "emergency=access_point",
            "Emergency Phone" to "emergency=phone",
            "Emergency Ward Entrance" to "emergency=emergency_ward_entrance",
            "Fire Alarm Box" to "emergency=fire_alarm_box",
            "Fire Extinguisher" to "emergency=fire_extinguisher",
            "Fire Hose" to "emergency=fire_hose",
            "Fire Hydrant" to "emergency=fire_hydrant",
            "Fire Service Inlet" to "emergency=fire_service_inlet",
            "First Aid Kit" to "emergency=first_aid_kit",
            "Landing Site" to "emergency=landing_site",
            "Life Ring" to "emergency=life_ring",
            "Lifeguard Base" to "emergency=lifeguard_base",
            "Lifeguard Platform" to "emergency=lifeguard_platform",
            "Lifeguard Tower" to "emergency=lifeguard_tower",
            "Siren" to "emergency=siren",
            "Suction Point" to "emergency=suction_point",
            "Water Tank (Emergency)" to "emergency=water_tank"
        ),

        "Tourism & Accommodation" to linkedMapOf(
            "Alpine Hut" to "tourism=alpine_hut",
            "Apartment (Tourism)" to "tourism=apartment",
            "Aquarium" to "tourism=aquarium",
            "Artwork" to "tourism=artwork",
            "Attraction" to "tourism=attraction",
            "Camp Pitch" to "tourism=camp_pitch",
            "Camp Site" to "tourism=camp_site",
            "Caravan Site" to "tourism=caravan_site",
            "Chalet" to "tourism=chalet",
            "Gallery" to "tourism=gallery",
            "Guest House" to "tourism=guest_house",
            "Hostel" to "tourism=hostel",
            "Hotel" to "tourism=hotel",
            "Information" to "tourism=information",
            "Tourist Information Office" to "information=office",
            "Information Board" to "information=board",
            "Information Terminal" to "information=terminal",
            "Motel" to "tourism=motel",
            "Museum" to "tourism=museum",
            "Picnic Site" to "tourism=picnic_site",
            "Theme Park" to "tourism=theme_park",
            "Viewpoint" to "tourism=viewpoint",
            "Wilderness Hut" to "tourism=wilderness_hut",
            "Zoo" to "tourism=zoo"
        ),

        "Historic" to linkedMapOf(
            "Aircraft (Historic)" to "historic=aircraft",
            "Archaeological Site" to "historic=archaeological_site",
            "Battlefield" to "historic=battlefield",
            "Bomb Crater" to "historic=bomb_crater",
            "Boundary Stone" to "historic=boundary_stone",
            "Building (Historic)" to "historic=building",
            "Cannon" to "historic=cannon",
            "Castle" to "historic=castle",
            "Castle Wall" to "historic=castle_wall",
            "Charcoal Pile" to "historic=charcoal_pile",
            "Church (Historic)" to "historic=church",
            "City Gate" to "historic=city_gate",
            "Citywalls" to "historic=citywalls",
            "Farm (Historic)" to "historic=farm",
            "Fort" to "historic=fort",
            "Gallows" to "historic=gallows",
            "Highwater Mark" to "historic=highwater_mark",
            "Locomotive" to "historic=locomotive",
            "Manor" to "historic=manor",
            "Memorial" to "historic=memorial",
            "Milestone (Historic)" to "historic=milestone",
            "Mine (Historic)" to "historic=mine",
            "Mine Shaft (Historic)" to "historic=mine_shaft",
            "Monument" to "historic=monument",
            "Pillory" to "historic=pillory",
            "Railway Car" to "historic=railway_car",
            "Ruins" to "historic=ruins",
            "Rune Stone" to "historic=rune_stone",
            "Ship" to "historic=ship",
            "Shipwreck" to "historic=wreck",
            "Tank (Historic)" to "historic=tank",
            "Tomb" to "historic=tomb",
            "Tower (Historic)" to "historic=tower",
            "Wayside Cross" to "historic=wayside_cross",
            "Wayside Shrine" to "historic=wayside_shrine"
        ),

        "Sports" to linkedMapOf(
            "American Football" to "sport=american_football",
            "Athletics" to "sport=athletics",
            "Badminton Court" to "sport=badminton",
            "Baseball Diamond" to "sport=baseball",
            "Basketball Court" to "sport=basketball",
            "Boules / Petanque" to "sport=boules",
            "Bowls" to "sport=bowls",
            "Chess Tables" to "sport=chess",
            "Climbing" to "sport=climbing",
            "Cricket Field" to "sport=cricket",
            "Cycling" to "sport=cycling",
            "Darts" to "sport=darts",
            "Equestrian" to "sport=equestrian",
            "Golf (Sport)" to "sport=golf",
            "Gymnastics" to "sport=gymnastics",
            "Handball" to "sport=handball",
            "Hockey Pitch" to "sport=hockey",
            "Ice Hockey" to "sport=ice_hockey",
            "Karting" to "sport=karting",
            "Motocross" to "sport=motocross",
            "Multi-Sport" to "sport=multi",
            "Padel" to "sport=padel",
            "Pickleball" to "sport=pickleball",
            "Rugby Pitch" to "sport=rugby",
            "Running Track" to "sport=running",
            "Scuba Diving" to "sport=scuba_diving",
            "Shooting Range" to "sport=shooting",
            "Skate Park" to "sport=skateboard",
            "Skiing" to "sport=skiing",
            "Soccer Field" to "sport=soccer",
            "Surfing" to "sport=surfing",
            "Swimming" to "sport=swimming",
            "Table Tennis (Ping Pong)" to "sport=table_tennis",
            "Tennis Court" to "sport=tennis",
            "Volleyball Court" to "sport=volleyball",
            "Yoga" to "sport=yoga"
        ),

        "Leisure & Recreation" to linkedMapOf(
            "Adult Gaming Centre" to "leisure=adult_gaming_centre",
            "Amusement Arcade" to "leisure=amusement_arcade",
            "Bandstand" to "leisure=bandstand",
            "Beach Resort" to "leisure=beach_resort",
            "Bird Hide" to "leisure=bird_hide",
            "Bleachers" to "leisure=bleachers",
            "Bowling Alley" to "leisure=bowling_alley",
            "Common" to "leisure=common",
            "Dance" to "leisure=dance",
            "Disc Golf Course" to "leisure=disc_golf_course",
            "Dog Park" to "leisure=dog_park",
            "Escape Game" to "leisure=escape_game",
            "Firepit" to "leisure=firepit",
            "Fishing" to "leisure=fishing",
            "Fitness Centre" to "leisure=fitness_centre",
            "Fitness Station" to "leisure=fitness_station",
            "Garden" to "leisure=garden",
            "Golf Course" to "leisure=golf_course",
            "Hackerspace" to "leisure=hackerspace",
            "Horse Riding" to "leisure=horse_riding",
            "Ice Rink" to "leisure=ice_rink",
            "Miniature Golf" to "leisure=miniature_golf",
            "Nature Reserve" to "leisure=nature_reserve",
            "Outdoor Seating" to "leisure=outdoor_seating",
            "Park" to "leisure=park",
            "Pitch" to "leisure=pitch",
            "Playground" to "leisure=playground",
            "Resort" to "leisure=resort",
            "Sauna" to "leisure=sauna",
            "Sports Centre" to "leisure=sports_centre",
            "Sports Hall" to "leisure=sports_hall",
            "Stadium" to "leisure=stadium",
            "Summer Camp" to "leisure=summer_camp",
            "Swimming Area" to "leisure=swimming_area",
            "Swimming Pool" to "leisure=swimming_pool",
            "Track" to "leisure=track",
            "Trampoline Park" to "leisure=trampoline_park",
            "Water Park" to "leisure=water_park"
        ),

        "Nature & Geography" to linkedMapOf(
            "Arch (Rock)" to "natural=arch",
            "Bare Rock" to "natural=bare_rock",
            "Bay" to "natural=bay",
            "Beach" to "natural=beach",
            "Cape" to "natural=cape",
            "Cave Entrance" to "natural=cave_entrance",
            "Cliff" to "natural=cliff",
            "Coastline" to "natural=coastline",
            "Dune" to "natural=dune",
            "Fell" to "natural=fell",
            "Geyser" to "natural=geyser",
            "Glacier" to "natural=glacier",
            "Grassland" to "natural=grassland",
            "Heath" to "natural=heath",
            "Hot Spring" to "natural=hot_spring",
            "Mud" to "natural=mud",
            "Peak (Summit)" to "natural=peak",
            "Reef" to "natural=reef",
            "Ridge" to "natural=ridge",
            "Rock" to "natural=rock",
            "Saddle" to "natural=saddle",
            "Sand" to "natural=sand",
            "Scree" to "natural=scree",
            "Scrub" to "natural=scrub",
            "Shingle" to "natural=shingle",
            "Sinkhole" to "natural=sinkhole",
            "Spring" to "natural=spring",
            "Stone" to "natural=stone",
            "Strait" to "natural=strait",
            "Tree" to "natural=tree",
            "Tree Row" to "natural=tree_row",
            "Valley" to "natural=valley",
            "Volcano" to "natural=volcano",
            "Water" to "natural=water",
            "Waterfall" to "waterway=waterfall",
            "Wetland" to "natural=wetland",
            "Wood" to "natural=wood",
            "Moraine" to "geological=moraine",
            "Outcrop" to "geological=outcrop",
            "Palaeontological Site" to "geological=palaeontological_site",
            "Volcanic Caldera" to "geological=volcanic_caldera_rim",
            "Volcanic Lava Flow" to "geological=volcanic_lava_flow",
            "Volcanic Vent" to "geological=volcanic_vent"
        ),

        "Land Use & Areas" to linkedMapOf(
            "Allotments" to "landuse=allotments",
            "Cemetery" to "landuse=cemetery",
            "Farmland" to "landuse=farmland",
            "Forest (Managed)" to "landuse=forest",
            "Meadow" to "landuse=meadow",
            "Orchard" to "landuse=orchard",
            "Quarry" to "landuse=quarry",
            "Recreation Ground" to "landuse=recreation_ground",
            "Reservoir" to "landuse=reservoir OR water=reservoir",
            "Vineyard" to "landuse=vineyard"
        ),

        "Places & Settlements" to linkedMapOf(
            "City" to "place=city",
            "Town" to "place=town",
            "Village" to "place=village",
            "Hamlet" to "place=hamlet",
            "Suburb" to "place=suburb",
            "Neighbourhood" to "place=neighbourhood",
            "Island" to "place=island",
            "Locality" to "place=locality"
        ),

        "Man-Made Structures" to linkedMapOf(
            "Adit" to "man_made=adit",
            "Antenna" to "man_made=antenna",
            "Breakwater" to "man_made=breakwater",
            "Bridge" to "bridge=yes",
            "Bunker Silo" to "man_made=bunker_silo",
            "Cairn (Rock Pile)" to "man_made=cairn",
            "Cellar Entrance" to "man_made=cellar_entrance",
            "Chimney" to "man_made=chimney",
            "Clearcut" to "man_made=clearcut",
            "Communications Tower" to "man_made=communications_tower",
            "Crane" to "man_made=crane",
            "Cross" to "man_made=cross",
            "Cutline" to "man_made=cutline",
            "Dovecote" to "man_made=dovecote",
            "Dyke" to "man_made=dyke",
            "Embankment" to "man_made=embankment",
            "Flagpole" to "man_made=flagpole",
            "Gasometer" to "man_made=gasometer",
            "Groyne" to "man_made=groyne",
            "Kiln" to "man_made=kiln",
            "Manhole" to "man_made=manhole",
            "Mast" to "man_made=mast",
            "Maypole" to "man_made=maypole",
            "Mineshaft" to "man_made=mineshaft",
            "Monitoring Station" to "man_made=monitoring_station",
            "Obelisk" to "man_made=obelisk",
            "Observatory" to "man_made=observatory",
            "Offshore Platform" to "man_made=offshore_platform",
            "Oil Well" to "man_made=oil_well",
            "Petroleum Well" to "man_made=petroleum_well",
            "Pipeline" to "man_made=pipeline",
            "Pumping Station" to "man_made=pumping_station",
            "Reservoir Covered" to "man_made=reservoir_covered",
            "Silo" to "man_made=silo",
            "Snow Cannon" to "man_made=snow_cannon",
            "Snow Fence" to "man_made=snow_fence",
            "Snow Net" to "man_made=snow_net",
            "Storage Tank" to "man_made=storage_tank",
            "Street Cabinet" to "man_made=street_cabinet",
            "Surveillance" to "man_made=surveillance",
            "Survey Point" to "man_made=survey_point",
            "Telescope" to "man_made=telescope",
            "Tower" to "man_made=tower",
            "Tunnel" to "tunnel=yes",
            "Utility Pole" to "man_made=utility_pole",
            "Water Mill" to "man_made=water_mill",
            "Water Pump" to "man_made=water_pump",
            "Water Tap" to "man_made=water_tap",
            "Water Tower" to "man_made=water_tower",
            "Water Well" to "man_made=water_well",
            "Water Works" to "man_made=water_works",
            "Wildlife Crossing" to "man_made=wildlife_crossing",
            "Windmill" to "man_made=windmill",
            "Works" to "man_made=works"
        ),

        "Power & Utilities" to linkedMapOf(
            "Power Cable" to "power=cable",
            "Catenary Mast" to "power=catenary_mast",
            "Compensator" to "power=compensator",
            "Converter" to "power=converter",
            "Generator" to "power=generator",
            "Heliostat" to "power=heliostat",
            "Insulator" to "power=insulator",
            "Power Line" to "power=line",
            "Minor Power Line" to "power=minor_line",
            "Power Plant" to "power=plant",
            "Power Pole" to "power=pole",
            "Power Portal" to "power=portal",
            "Substation" to "power=substation",
            "Power Switch" to "power=switch",
            "Power Terminal" to "power=terminal",
            "Power Tower" to "power=tower",
            "Transformer" to "power=transformer"
        ),

        "Barriers & Access" to linkedMapOf(
            "Barrier (General)" to "barrier=yes",
            "Block" to "barrier=block",
            "Bollard" to "barrier=bollard",
            "Border Control" to "barrier=border_control",
            "Bump Gate" to "barrier=bump_gate",
            "Bus Trap" to "barrier=bus_trap",
            "Cable Barrier" to "barrier=cable_barrier",
            "Cattle Grid" to "barrier=cattle_grid",
            "Chain" to "barrier=chain",
            "City Wall" to "barrier=city_wall",
            "Cycle Barrier" to "barrier=cycle_barrier",
            "Debris" to "barrier=debris",
            "Ditch" to "barrier=ditch",
            "Fence" to "barrier=fence",
            "Full-height Turnstile" to "barrier=full-height_turnstile",
            "Gate" to "barrier=gate",
            "Guard Rail" to "barrier=guard_rail",
            "Hampshire Gate" to "barrier=hampshire_gate",
            "Handrail" to "barrier=handrail",
            "Hedge" to "barrier=hedge",
            "Height Restrictor" to "barrier=height_restrictor",
            "Horse Stile" to "barrier=horse_stile",
            "Jersey Barrier" to "barrier=jersey_barrier",
            "Kerb" to "barrier=kerb",
            "Kissing Gate" to "barrier=kissing_gate",
            "Lift Gate" to "barrier=lift_gate",
            "Log" to "barrier=log",
            "Motorcycle Barrier" to "barrier=motorcycle_barrier",
            "Retaining Wall" to "barrier=retaining_wall",
            "Rope" to "barrier=rope",
            "Sally Port" to "barrier=sally_port",
            "Sliding Gate" to "barrier=sliding_gate",
            "Spikes" to "barrier=spikes",
            "Stile (Fence Step)" to "barrier=stile",
            "Sump Buster" to "barrier=sump_buster",
            "Swing Gate" to "barrier=swing_gate",
            "Tank Trap" to "barrier=tank_trap",
            "Toll Booth" to "barrier=toll_booth",
            "Turnstile" to "barrier=turnstile",
            "Wall" to "barrier=wall",
            "Entrance" to "entrance=yes",
            "Main Entrance" to "entrance=main",
            "Service Entrance" to "entrance=service"
        ),

        "Military" to linkedMapOf(
            "Military Airfield" to "military=airfield",
            "Ammunition" to "military=ammunition",
            "Barracks" to "military=barracks",
            "Military Base" to "military=base",
            "Bunker" to "military=bunker",
            "Checkpoint" to "military=checkpoint",
            "Danger Area" to "military=danger_area",
            "Naval Base" to "military=naval_base",
            "Nuclear Explosion Site" to "military=nuclear_explosion_site",
            "Obstacle Course" to "military=obstacle_course",
            "Military Office" to "military=office",
            "Military Range" to "military=range",
            "Training Area" to "military=training_area",
            "Trench" to "military=trench"
        ),

        "Aerialways (Ski Lifts etc.)" to linkedMapOf(
            "Cable Car" to "aerialway=cable_car",
            "Chair Lift" to "aerialway=chair_lift",
            "Drag Lift" to "aerialway=drag_lift",
            "Gondola" to "aerialway=gondola",
            "Goods Ropeway" to "aerialway=goods",
            "J-bar" to "aerialway=j-bar",
            "Magic Carpet" to "aerialway=magic_carpet",
            "Mixed Lift" to "aerialway=mixed_lift",
            "Platter" to "aerialway=platter",
            "Pylon" to "aerialway=pylon",
            "Rope Tow" to "aerialway=rope_tow",
            "Aerialway Station" to "aerialway=station",
            "T-bar" to "aerialway=t-bar",
            "Zip Line" to "aerialway=zip_line"
        ),

        "Hiking & Navigation" to linkedMapOf(
            "Hiking Sign (Guidepost)" to "information=guidepost",
            "Map Board" to "information=map",
            "Trail Blaze" to "information=route_marker",
            "Trailhead" to "highway=trailhead",
            "Ski Piste Map" to "information=piste_map"
        ),

        "Vending Machines" to linkedMapOf(
            "Ticket Machine" to "vending=public_transport_tickets",
            "Parking Ticket Machine" to "vending=parking_tickets",
            "Drinks Machine" to "vending=drinks",
            "Coffee Machine" to "vending=coffee",
            "Water Vending" to "vending=water",
            "Snack Machine" to "vending=food",
            "Sweets Machine" to "vending=sweets",
            "Cigarette Machine" to "vending=cigarettes",
            "Condom Machine" to "vending=condoms",
            "Newspaper Box" to "vending=newspapers",
            "Stamp Machine" to "vending=stamps",
            "Bicycle Tube Machine" to "vending=bicycle_tube"
        ),

        "Playground Equipment" to linkedMapOf(
            "Slide" to "playground=slide",
            "Swing" to "playground=swing",
            "Sandpit" to "playground=sandpit",
            "Seesaw" to "playground=seesaw",
            "Climbing Frame" to "playground=structure",
            "Zipwire" to "playground=zipwire"
        ),

        "Streets & Navigation" to linkedMapOf(
            "Street Lamp" to "highway=street_lamp",
            "Stairs" to "highway=steps",
            "Elevator" to "highway=elevator",
            "Pedestrian Crossing" to "highway=crossing",
            "Traffic Signals" to "highway=traffic_signals",
            "Stop Sign" to "highway=stop",
            "Give Way Sign" to "highway=give_way",
            "Speed Camera" to "highway=speed_camera",
            "Traffic Mirror" to "highway=traffic_mirror",
            "Milestone" to "highway=milestone",
            "Passing Place" to "highway=passing_place",
            "Rest Area" to "highway=rest_area",
            "Motorway Services" to "highway=services",
            "Billboard" to "advertising=billboard",
            "Advertising Column" to "advertising=column"
        )
    )

    /** Flat name -> query lookup used everywhere else. */
    val mapping: Map<String, String> = LinkedHashMap<String, String>().apply {
        for ((_, items) in categories) putAll(items)
    }
}
